### ISSUE TITLE
Nice work! A couple of questions...

### ISSUE THREAD

**Issue by nlml** [pcl3dv/PSAvatar#2]
Thanks for releasing this great work!

I am just wondering, how long does it take to train your method? How long does each training phase take?

Also, could you perhaps show comparison videos with/without the Unet refiner network? I am curious how much that helps...

Thanks again!

**Comment by pcl3dv** [comment]
Thanks for your kind suggestion.  The newly attached video shows the effect of the enhancement operation.
The training is implemented based on Nvidia A100, and it takes about 2 hours to train subject 1 - subject 3, and around 5 hours for subject 4 - subject 6.

**Comment by nlml** [comment]
Amazing! Thanks a lot!
