### ISSUE TITLE
What FLAME-tracking algorithm is used?

### ISSUE THREAD

**Issue by ChikaYan** [pcl3dv/PSAvatar#5]
Hi,

Congrats on the amazing paper! The performance of the method looks awesome.

May I ask what FLAME-tracking method did you use to obtain the camera pose/flame parameters etc? In the paper it says you used the same algorithm for all datasets. Is it the preprocessing pipeline developed by INSTA/PointAvatar, or is it something you developed on your own?

Many thanks

**Comment by pcl3dv** [comment]
hi there,
thanks for your interests. The flame tracking is conducted using the method developed by IM Avatar.

**Comment by ChikaYan** [comment]
Thanks a lot!
